name: Docker Hub Publish

on:
  repository_dispatch:
    types: [dockerhub-publish]

jobs:
  call-reusable-dockerhub:
    uses: ai-pipestream/.github/.github/workflows/reusable-dockerhub-publish.yml@main
    with:
      base_image: ${{ github.event.client_payload.base_image }}
      dockerhub_repo: ${{ github.event.client_payload.dockerhub_repo }}
      tags: ${{ github.event.client_payload.tags }}
    secrets: inherit
